baseURL = "http://example.org/"
languageCode = "en-us"
title = "Nesakko"

# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

############################# Plugins #########################################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/Fork-Awesome/css/fork-awesome.min.css"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"

############################# Navigation ######################################
[[menu.main]]
name = "About Us"
URL = "about"
weight = 1

[[menu.main]]
name = "Portfolio"
URL = "portfolio"
weight = 2

[[menu.main]]
name = "Team"
URL = "team"
weight = 3

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 4

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 5

#### external / static link ####
#[[menu.static]]
#name = ""
#URL = ""
#weight = 6

############################# Default Parameters ##############################
[params]
#logo = "images/logo.png"
# Meta data
description = "Responsive Multipurpose Parallax HTML5 Template"
author = "Themefisher"

# post share
post_share = true

# preloader
[params.preloader]
enable = true
preloader = "images/logo.png"

############################# social icons ####################################
[[params.social]]
icon = "fa fa-twitter"
link = "https://twitter.com/Nesakko"

[[params.social]]
icon = "fa fa-mastodon"
link = "https://misskey.io/@Nesakko"

[[params.social]]
icon = "fa fa-diaspora"
link = "https://pod.dapor.net/people/61cec8f086010137677d48600054b5a3"

[[params.social]]
icon = "fa fa-pixelfed"
link = "https://pixelfed.de/Nesakko"

[[params.social]]
icon = "fa fa-github"
link = "https://github.com/Nesakko"

[[params.social]]
icon = "fa fa-deviantart"
link = "https://patreon.com/Nesakko"

[[params.social]]
icon = "fa fa-patreon"
link = "https://patreon.com/Nesakko"

################################ Language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
copyright = "© Nesakko"

[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
home = "Accueil"
copyright = "© Nesakko"
